name: NYT CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    on: [push, pull_request]
      push: 
        branches: [ main ]
    steps:
      - run: npm run build
      - run: npm run deploy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
